/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 website.gltf --transform 
Files: website.gltf [9.37MB] > C:\Users\moham\OneDrive\Desktop\website\website-transformed.glb [1.31MB] (86%)
Author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/artstation-website-ecd1e4c9b48f40068d0454efbf624bb0
Title: Artstation Website
*/

import { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Website(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('../../public/img/website-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group name="Circle_14" scale={114.753}>
            <group name="Cylinder001_0" position={[0, 0.359, 0]} scale={0.009}>
              <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials['Material.002']} />
            </group>
            <group name="Cylinder007_6" position={[0, 0.631, 0]} scale={0.007}>
              <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.material_0} />
            </group>
            <group name="Cylinder008_7" position={[0, 0.61, 0]} scale={0.006}>
              <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.material_0} />
            </group>
            <group name="Cylinder009_8" position={[0, 0.588, 0]} scale={0.005}>
              <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.material_0} />
            </group>
            <group name="Cylinder010_9" position={[0, 0.563, 0]} scale={0.004}>
              <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.material_0} />
            </group>
            <group name="Cylinder011_10" position={[0, 0.536, 0]} scale={0.003}>
              <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.material_0} />
            </group>
            <group name="Plane_11" position={[0.29, 0.357, 0.167]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.58, 0.003, 0.326]}>
              <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.material} />
            </group>
            <group name="Plane001_12" position={[0, 0.357, -0.335]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.58, 0.003, 0.326]}>
              <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.material_3} />
            </group>
            <group name="Plane002_13" position={[-0.29, 0.357, 0.168]} scale={[0.58, 0.003, 0.326]}>
              <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.material_4} />
            </group>
          </group>
          <group name="Circle001_25" position={[0, 89.248, 0]} scale={25.293}>
            <group name="Plane004_16" position={[0, -0.043, -0.064]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.material_6} />
            </group>
            <group name="Plane006_17" position={[0, -0.043, -0.047]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.material_6} />
            </group>
            <group name="Plane007_18" position={[0, -0.043, -0.038]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.material_6} />
            </group>
            <group name="Plane008_19" position={[0, -0.043, -0.03]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.material_6} />
            </group>
            <group name="Plane009_20" position={[0, -0.043, -0.022]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.material_6} />
            </group>
            <group name="Plane012_21" position={[0, -0.043, 0.003]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.material_6} />
            </group>
            <group name="Plane013_22" position={[0, -0.043, 0.012]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.material_6} />
            </group>
            <group name="Plane014_23" position={[0, -0.043, 0.021]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.material_6} />
            </group>
            <group name="Plane016_24" position={[0, -0.043, 0.038]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.material_6} />
            </group>
          </group>
          <group name="Circle002_37" position={[0, 89.248, 0]} scale={25.293}>
            <group name="Plane021_26" position={[0, -0.043, -0.073]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_45" geometry={nodes.Object_45.geometry} material={materials.material_6} />
            </group>
            <group name="Plane023_27" position={[0, -0.043, -0.056]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.material_6} />
            </group>
            <group name="Plane027_28" position={[0, -0.043, -0.022]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.material_6} />
            </group>
            <group name="Plane028_29" position={[0, -0.043, -0.013]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_51" geometry={nodes.Object_51.geometry} material={materials.material_6} />
            </group>
            <group name="Plane029_30" position={[0, -0.043, -0.004]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials.material_6} />
            </group>
            <group name="Plane030_31" position={[0, -0.043, 0.003]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_55" geometry={nodes.Object_55.geometry} material={materials.material_6} />
            </group>
            <group name="Plane033_32" position={[0, -0.043, 0.029]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_57" geometry={nodes.Object_57.geometry} material={materials.material_6} />
            </group>
            <group name="Plane035_33" position={[0, -0.043, 0.047]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_59" geometry={nodes.Object_59.geometry} material={materials.material_6} />
            </group>
            <group name="Plane036_34" position={[0, -0.043, 0.054]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_61" geometry={nodes.Object_61.geometry} material={materials.material_6} />
            </group>
            <group name="Plane037_35" position={[0, -0.043, 0.063]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_63" geometry={nodes.Object_63.geometry} material={materials.material_6} />
            </group>
            <group name="Plane038_36" position={[0, -0.043, 0.072]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.material_6} />
            </group>
          </group>
          <group name="Circle004_48" position={[0, 89.248, 0]} scale={25.293}>
            <group name="Plane003_39" position={[0, -0.043, -0.064]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.material_7} />
            </group>
            <group name="Plane005_40" position={[0, -0.043, -0.047]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.material_7} />
            </group>
            <group name="Plane010_41" position={[0, -0.043, -0.038]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.material_7} />
            </group>
            <group name="Plane011_42" position={[0, -0.043, -0.03]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.material_7} />
            </group>
            <group name="Plane015_43" position={[0, -0.043, -0.022]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials.material_7} />
            </group>
            <group name="Plane017_44" position={[0, -0.043, 0.003]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.material_7} />
            </group>
            <group name="Plane018_45" position={[0, -0.043, 0.012]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.material_7} />
            </group>
            <group name="Plane019_46" position={[0, -0.043, 0.021]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials.material_7} />
            </group>
            <group name="Plane020_47" position={[0, -0.043, 0.038]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.material_7} />
            </group>
          </group>
          <group name="Circle005_60" position={[0, 89.248, 0]} scale={25.293}>
            <group name="Plane022_49" position={[0, -0.043, -0.073]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_87" geometry={nodes.Object_87.geometry} material={materials.material_7} />
            </group>
            <group name="Plane024_50" position={[0, -0.043, -0.056]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_89" geometry={nodes.Object_89.geometry} material={materials.material_7} />
            </group>
            <group name="Plane025_51" position={[0, -0.043, -0.022]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_91" geometry={nodes.Object_91.geometry} material={materials.material_7} />
            </group>
            <group name="Plane026_52" position={[0, -0.043, -0.013]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_93" geometry={nodes.Object_93.geometry} material={materials.material_7} />
            </group>
            <group name="Plane031_53" position={[0, -0.043, -0.004]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_95" geometry={nodes.Object_95.geometry} material={materials.material_7} />
            </group>
            <group name="Plane032_54" position={[0, -0.043, 0.003]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_97" geometry={nodes.Object_97.geometry} material={materials.material_7} />
            </group>
            <group name="Plane034_55" position={[0, -0.043, 0.029]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_99" geometry={nodes.Object_99.geometry} material={materials.material_7} />
            </group>
            <group name="Plane039_56" position={[0, -0.043, 0.047]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_101" geometry={nodes.Object_101.geometry} material={materials.material_7} />
            </group>
            <group name="Plane040_57" position={[0, -0.043, 0.054]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_103" geometry={nodes.Object_103.geometry} material={materials.material_7} />
            </group>
            <group name="Plane041_58" position={[0, -0.043, 0.063]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_105" geometry={nodes.Object_105.geometry} material={materials.material_7} />
            </group>
            <group name="Plane042_59" position={[0, -0.043, 0.072]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_107" geometry={nodes.Object_107.geometry} material={materials.material_7} />
            </group>
          </group>
          <group name="Circle007_71" position={[0, 89.248, 0]} scale={25.293}>
            <group name="Plane043_62" position={[0, -0.043, -0.064]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials.material_8} />
            </group>
            <group name="Plane044_63" position={[0, -0.043, -0.047]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.material_8} />
            </group>
            <group name="Plane045_64" position={[0, -0.043, -0.038]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials.material_8} />
            </group>
            <group name="Plane046_65" position={[0, -0.043, -0.03]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials.material_8} />
            </group>
            <group name="Plane047_66" position={[0, -0.043, -0.022]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials.material_8} />
            </group>
            <group name="Plane048_67" position={[0, -0.043, 0.003]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials.material_8} />
            </group>
            <group name="Plane049_68" position={[0, -0.043, 0.012]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_122" geometry={nodes.Object_122.geometry} material={materials.material_8} />
            </group>
            <group name="Plane050_69" position={[0, -0.043, 0.021]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials.material_8} />
            </group>
            <group name="Plane051_70" position={[0, -0.043, 0.038]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_126" geometry={nodes.Object_126.geometry} material={materials.material_8} />
            </group>
          </group>
          <group name="Circle008_83" position={[0, 89.248, 0]} scale={25.293}>
            <group name="Plane052_72" position={[0, -0.043, -0.073]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_129" geometry={nodes.Object_129.geometry} material={materials.material_8} />
            </group>
            <group name="Plane053_73" position={[0, -0.043, -0.056]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_131" geometry={nodes.Object_131.geometry} material={materials.material_8} />
            </group>
            <group name="Plane054_74" position={[0, -0.043, -0.022]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_133" geometry={nodes.Object_133.geometry} material={materials.material_8} />
            </group>
            <group name="Plane055_75" position={[0, -0.043, -0.013]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_135" geometry={nodes.Object_135.geometry} material={materials.material_8} />
            </group>
            <group name="Plane056_76" position={[0, -0.043, -0.004]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_137" geometry={nodes.Object_137.geometry} material={materials.material_8} />
            </group>
            <group name="Plane057_77" position={[0, -0.043, 0.003]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_139" geometry={nodes.Object_139.geometry} material={materials.material_8} />
            </group>
            <group name="Plane058_78" position={[0, -0.043, 0.029]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_141" geometry={nodes.Object_141.geometry} material={materials.material_8} />
            </group>
            <group name="Plane059_79" position={[0, -0.043, 0.047]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_143" geometry={nodes.Object_143.geometry} material={materials.material_8} />
            </group>
            <group name="Plane060_80" position={[0, -0.043, 0.054]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_145" geometry={nodes.Object_145.geometry} material={materials.material_8} />
            </group>
            <group name="Plane061_81" position={[0, -0.043, 0.063]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_147" geometry={nodes.Object_147.geometry} material={materials.material_8} />
            </group>
            <group name="Plane062_82" position={[0, -0.043, 0.072]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.503, 0.547, 0.503]}>
              <mesh name="Object_149" geometry={nodes.Object_149.geometry} material={materials.material_8} />
            </group>
          </group>
          <group name="Cube_85" position={[111.626, -6.906, -99.978]} scale={0}>
            <mesh name="Object_151" geometry={nodes.Object_151.geometry} material={materials.shoo} />
          </group>
          <group name="Cube001_86" position={[-127.136, -6.906, -104.721]} scale={0}>
            <mesh name="Object_153" geometry={nodes.Object_153.geometry} material={materials.shoo} />
          </group>
          <group name="Cube002_87" position={[31.93, -6.906, 103.083]} scale={0}>
            <mesh name="Object_155" geometry={nodes.Object_155.geometry} material={materials.shoo} />
          </group>
          <group name="Cube003_88" position={[-96.427, -6.906, 74.418]} scale={0}>
            <mesh name="Object_157" geometry={nodes.Object_157.geometry} material={materials.shoo} />
          </group>
          <group name="Cube004_89" position={[-167.152, -6.906, 58.306]} scale={0}>
            <mesh name="Object_159" geometry={nodes.Object_159.geometry} material={materials.shoo} />
          </group>
          <group name="Cube005_90" position={[-6.219, -6.906, 174.189]} scale={0}>
            <mesh name="Object_161" geometry={nodes.Object_161.geometry} material={materials.shoo} />
          </group>
          <group name="Cube006_91" position={[100.018, -6.906, 30.416]} scale={0}>
            <mesh name="Object_163" geometry={nodes.Object_163.geometry} material={materials.shoo} />
          </group>
          <group name="Cube007_92" position={[101.698, -6.906, 95.981]} scale={0}>
            <mesh name="Object_165" geometry={nodes.Object_165.geometry} material={materials.shoo} />
          </group>
          <group name="Cube008_93" position={[108.699, -6.906, -23.413]} scale={0}>
            <mesh name="Object_167" geometry={nodes.Object_167.geometry} material={materials.shoo} />
          </group>
          <group name="Cube009_94" position={[15.071, -6.906, -198.234]} scale={0}>
            <mesh name="Object_169" geometry={nodes.Object_169.geometry} material={materials.shoo} />
          </group>
          <group name="Cube010_95" position={[-113.158, -6.906, -28.371]} scale={0}>
            <mesh name="Object_171" geometry={nodes.Object_171.geometry} material={materials.shoo} />
          </group>
          <group name="Cube011_96" position={[-116.237, -6.906, -175.413]} scale={0}>
            <mesh name="Object_173" geometry={nodes.Object_173.geometry} material={materials.shoo} />
          </group>
          <group name="Cube012_97" position={[43.392, -6.906, 137.645]} scale={0}>
            <mesh name="Object_175" geometry={nodes.Object_175.geometry} material={materials.shoo} />
          </group>
          <group name="Cube013_98" position={[123.894, -6.906, -87.186]} scale={0}>
            <mesh name="Object_177" geometry={nodes.Object_177.geometry} material={materials.shoo} />
          </group>
          <group name="Cube014_99" position={[-123.736, -6.906, -2.546]} scale={0}>
            <mesh name="Object_179" geometry={nodes.Object_179.geometry} material={materials.shoo} />
          </group>
          <group name="Cube015_100" position={[-55.702, -6.906, -115.101]} scale={0}>
            <mesh name="Object_181" geometry={nodes.Object_181.geometry} material={materials.shoo} />
          </group>
          <group name="Cube016_101" position={[-17.914, -6.906, -177.018]} scale={0}>
            <mesh name="Object_183" geometry={nodes.Object_183.geometry} material={materials.shoo} />
          </group>
          <group name="Cube017_102" position={[-178.999, -6.906, -61.346]} scale={0}>
            <mesh name="Object_185" geometry={nodes.Object_185.geometry} material={materials.shoo} />
          </group>
          <group name="Cube018_103" position={[-76.524, -6.906, 85.133]} scale={0}>
            <mesh name="Object_187" geometry={nodes.Object_187.geometry} material={materials.shoo} />
          </group>
          <group name="Cube019_104" position={[-139.213, -6.906, 65.854]} scale={0}>
            <mesh name="Object_189" geometry={nodes.Object_189.geometry} material={materials.shoo} />
          </group>
          <group name="Cube020_105" position={[-28.259, -6.906, 110.498]} scale={0}>
            <mesh name="Object_191" geometry={nodes.Object_191.geometry} material={materials.shoo} />
          </group>
          <group name="Cube021_106" position={[167.272, -6.906, 77.392]} scale={0}>
            <mesh name="Object_193" geometry={nodes.Object_193.geometry} material={materials.shoo} />
          </group>
          <group name="Cube022_107" position={[47.066, -6.906, -98.24]} scale={0}>
            <mesh name="Object_195" geometry={nodes.Object_195.geometry} material={materials.shoo} />
          </group>
          <group name="Cube023_108" position={[187.439, -6.906, -54.35]} scale={0}>
            <mesh name="Object_197" geometry={nodes.Object_197.geometry} material={materials.shoo} />
          </group>
          <group name="Cube024_109" position={[111.626, 164.374, -99.978]} scale={[0.6, 44.086, 0.6]}>
            <mesh name="Object_199" geometry={nodes.Object_199.geometry} material={materials.shoo} />
          </group>
          <group name="Cube025_110" position={[-127.136, 206.551, -104.721]} scale={[0.6, 53.728, 0.6]}>
            <mesh name="Object_201" geometry={nodes.Object_201.geometry} material={materials.shoo} />
          </group>
          <group name="Cube026_111" position={[31.93, 223.873, 103.083]} scale={[0.6, 57.554, 0.6]}>
            <mesh name="Object_203" geometry={nodes.Object_203.geometry} material={materials.shoo} />
          </group>
          <group name="Cube027_112" position={[-96.427, 244.977, 74.418]} scale={[0.6, 61.823, 0.6]}>
            <mesh name="Object_205" geometry={nodes.Object_205.geometry} material={materials.shoo} />
          </group>
          <group name="Cube028_113" position={[-167.152, 238.884, 58.306]} scale={[0.6, 60.503, 0.6]}>
            <mesh name="Object_207" geometry={nodes.Object_207.geometry} material={materials.shoo} />
          </group>
          <group name="Cube029_114" position={[-6.219, 248.443, 174.189]} scale={[0.6, 62.605, 0.6]}>
            <mesh name="Object_209" geometry={nodes.Object_209.geometry} material={materials.shoo} />
          </group>
          <group name="Cube030_115" position={[100.018, 251.661, 30.416]} scale={[0.6, 63.286, 0.6]}>
            <mesh name="Object_211" geometry={nodes.Object_211.geometry} material={materials.shoo} />
          </group>
          <group name="Cube031_116" position={[101.698, 249.755, 95.981]} scale={0}>
            <mesh name="Object_213" geometry={nodes.Object_213.geometry} material={materials.shoo} />
          </group>
          <group name="Cube032_117" position={[108.699, -3.113, -23.413]} scale={[0.6, 2.729, 0.6]}>
            <mesh name="Object_215" geometry={nodes.Object_215.geometry} material={materials.shoo} />
          </group>
          <group name="Cube033_118" position={[15.071, 57.45, -198.234]} scale={[0.6, 20.127, 0.6]}>
            <mesh name="Object_217" geometry={nodes.Object_217.geometry} material={materials.shoo} />
          </group>
          <group name="Cube034_119" position={[-113.158, 100.606, -28.371]} scale={[0.6, 30.839, 0.6]}>
            <mesh name="Object_219" geometry={nodes.Object_219.geometry} material={materials.shoo} />
          </group>
          <group name="Cube035_120" position={[-116.237, 68.955, -175.413]} scale={[0.6, 22.106, 0.6]}>
            <mesh name="Object_221" geometry={nodes.Object_221.geometry} material={materials.shoo} />
          </group>
          <group name="Cube036_121" position={[43.392, 23.818, 137.645]} scale={[0.6, 10.814, 0.6]}>
            <mesh name="Object_223" geometry={nodes.Object_223.geometry} material={materials.shoo} />
          </group>
          <group name="Cube037_122" position={[123.894, 96.984, -87.186]} scale={[0.6, 29.483, 0.6]}>
            <mesh name="Object_225" geometry={nodes.Object_225.geometry} material={materials.shoo} />
          </group>
          <group name="Cube038_123" position={[-123.736, 136.789, -2.546]} scale={[0.6, 38.939, 0.6]}>
            <mesh name="Object_227" geometry={nodes.Object_227.geometry} material={materials.shoo} />
          </group>
          <group name="Cube039_124" position={[-55.702, 123.196, -115.101]} scale={[0.6, 34.777, 0.6]}>
            <mesh name="Object_229" geometry={nodes.Object_229.geometry} material={materials.shoo} />
          </group>
          <group name="Cube040_125" position={[-17.914, 109.28, -177.018]} scale={[0.6, 31.579, 0.6]}>
            <mesh name="Object_231" geometry={nodes.Object_231.geometry} material={materials.shoo} />
          </group>
          <group name="Cube041_126" position={[-178.999, 169.729, -61.346]} scale={[0.6, 45.766, 0.6]}>
            <mesh name="Object_233" geometry={nodes.Object_233.geometry} material={materials.shoo} />
          </group>
          <group name="Cube042_127" position={[-76.524, 196.329, 85.133]} scale={[0.6, 51.775, 0.6]}>
            <mesh name="Object_235" geometry={nodes.Object_235.geometry} material={materials.shoo} />
          </group>
          <group name="Cube043_128" position={[-139.213, 212.641, 65.854]} scale={[0.6, 54.777, 0.6]}>
            <mesh name="Object_237" geometry={nodes.Object_237.geometry} material={materials.shoo} />
          </group>
          <group name="Cube044_129" position={[-28.259, 11.716, 110.498]} scale={0}>
            <mesh name="Object_239" geometry={nodes.Object_239.geometry} material={materials.shoo} />
          </group>
          <group name="Cube045_130" position={[167.272, -6.346, 77.392]} scale={[0.6, 1.295, 0.6]}>
            <mesh name="Object_241" geometry={nodes.Object_241.geometry} material={materials.shoo} />
          </group>
          <group name="Cube046_131" position={[47.066, 16.762, -98.24]} scale={[0.6, 10.04, 0.6]}>
            <mesh name="Object_243" geometry={nodes.Object_243.geometry} material={materials.shoo} />
          </group>
          <group name="Cube047_132" position={[187.439, -6.651, -54.35]} scale={0}>
            <mesh name="Object_245" geometry={nodes.Object_245.geometry} material={materials.shoo} />
          </group>
          <group name="Cube048_133" position={[111.626, -6.906, -99.978]} scale={0}>
            <mesh name="Object_247" geometry={nodes.Object_247.geometry} material={materials.shoo} />
          </group>
          <group name="Cube049_134" position={[-127.136, -6.906, -104.721]} scale={0}>
            <mesh name="Object_249" geometry={nodes.Object_249.geometry} material={materials.shoo} />
          </group>
          <group name="Cube050_135" position={[31.93, -6.906, 103.083]} scale={0}>
            <mesh name="Object_251" geometry={nodes.Object_251.geometry} material={materials.shoo} />
          </group>
          <group name="Cube051_136" position={[-96.427, -6.906, 74.418]} scale={0}>
            <mesh name="Object_253" geometry={nodes.Object_253.geometry} material={materials.shoo} />
          </group>
          <group name="Cube052_137" position={[-167.152, -6.906, 58.306]} scale={0}>
            <mesh name="Object_255" geometry={nodes.Object_255.geometry} material={materials.shoo} />
          </group>
          <group name="Cube053_138" position={[-6.219, -6.906, 174.189]} scale={0}>
            <mesh name="Object_257" geometry={nodes.Object_257.geometry} material={materials.shoo} />
          </group>
          <group name="Cube054_139" position={[100.018, -6.906, 30.416]} scale={0}>
            <mesh name="Object_259" geometry={nodes.Object_259.geometry} material={materials.shoo} />
          </group>
          <group name="Cube055_140" position={[101.698, -6.906, 95.981]} scale={0}>
            <mesh name="Object_261" geometry={nodes.Object_261.geometry} material={materials.shoo} />
          </group>
          <group name="Cube056_141" position={[108.699, -6.906, -23.413]} scale={0}>
            <mesh name="Object_263" geometry={nodes.Object_263.geometry} material={materials.shoo} />
          </group>
          <group name="Cube057_142" position={[15.071, -6.906, -198.234]} scale={0}>
            <mesh name="Object_265" geometry={nodes.Object_265.geometry} material={materials.shoo} />
          </group>
          <group name="Cube058_143" position={[-113.158, -6.906, -28.371]} scale={0}>
            <mesh name="Object_267" geometry={nodes.Object_267.geometry} material={materials.shoo} />
          </group>
          <group name="Cube059_144" position={[-116.237, -6.906, -175.413]} scale={0}>
            <mesh name="Object_269" geometry={nodes.Object_269.geometry} material={materials.shoo} />
          </group>
          <group name="Cube060_145" position={[43.392, -6.906, 137.645]} scale={0}>
            <mesh name="Object_271" geometry={nodes.Object_271.geometry} material={materials.shoo} />
          </group>
          <group name="Cube061_146" position={[123.894, -6.906, -87.186]} scale={0}>
            <mesh name="Object_273" geometry={nodes.Object_273.geometry} material={materials.shoo} />
          </group>
          <group name="Cube062_147" position={[-123.736, -6.906, -2.546]} scale={0}>
            <mesh name="Object_275" geometry={nodes.Object_275.geometry} material={materials.shoo} />
          </group>
          <group name="Cube063_148" position={[-55.702, -6.906, -115.101]} scale={0}>
            <mesh name="Object_277" geometry={nodes.Object_277.geometry} material={materials.shoo} />
          </group>
          <group name="Cube064_149" position={[-17.914, -6.906, -177.018]} scale={0}>
            <mesh name="Object_279" geometry={nodes.Object_279.geometry} material={materials.shoo} />
          </group>
          <group name="Cube065_150" position={[-178.999, -6.906, -61.346]} scale={0}>
            <mesh name="Object_281" geometry={nodes.Object_281.geometry} material={materials.shoo} />
          </group>
          <group name="Cube066_151" position={[-76.524, -6.906, 85.133]} scale={0}>
            <mesh name="Object_283" geometry={nodes.Object_283.geometry} material={materials.shoo} />
          </group>
          <group name="Cube067_152" position={[-139.213, -6.906, 65.854]} scale={0}>
            <mesh name="Object_285" geometry={nodes.Object_285.geometry} material={materials.shoo} />
          </group>
          <group name="Cube068_153" position={[-28.259, -6.906, 110.498]} scale={0}>
            <mesh name="Object_287" geometry={nodes.Object_287.geometry} material={materials.shoo} />
          </group>
          <group name="Cube069_154" position={[167.272, -6.906, 77.392]} scale={0}>
            <mesh name="Object_289" geometry={nodes.Object_289.geometry} material={materials.shoo} />
          </group>
          <group name="Cube070_155" position={[47.066, -6.906, -98.24]} scale={0}>
            <mesh name="Object_291" geometry={nodes.Object_291.geometry} material={materials.shoo} />
          </group>
          <group name="Cube071_156" position={[187.439, -6.906, -54.35]} scale={0}>
            <mesh name="Object_293" geometry={nodes.Object_293.geometry} material={materials.shoo} />
          </group>
          <group name="Cube072_257" position={[-9.448, 55.777, 14.465]} scale={0}>
            <mesh name="Object_295" geometry={nodes.Object_295.geometry} material={materials.shoo} />
          </group>
          <group name="Cube073_258" position={[17.283, 55.777, 7.868]} scale={0}>
            <mesh name="Object_297" geometry={nodes.Object_297.geometry} material={materials.shoo} />
          </group>
          <group name="Cube074_259" position={[-6.632, 55.777, -10.527]} scale={0}>
            <mesh name="Object_299" geometry={nodes.Object_299.geometry} material={materials.shoo} />
          </group>
          <group name="Cube075_260" position={[8.518, 55.777, -11.165]} scale={0}>
            <mesh name="Object_301" geometry={nodes.Object_301.geometry} material={materials.shoo} />
          </group>
          <group name="Cube076_261" position={[16.875, 55.777, -11.481]} scale={0}>
            <mesh name="Object_303" geometry={nodes.Object_303.geometry} material={materials.shoo} />
          </group>
          <group name="Cube077_262" position={[-4.505, 55.777, -19.584]} scale={0}>
            <mesh name="Object_305" geometry={nodes.Object_305.geometry} material={materials.shoo} />
          </group>
          <group name="Cube078_263" position={[-12.046, 55.777, -0.403]} scale={0}>
            <mesh name="Object_307" geometry={nodes.Object_307.geometry} material={materials.shoo} />
          </group>
          <group name="Cube079_264" position={[-14.19, 55.777, -7.654]} scale={0}>
            <mesh name="Object_309" geometry={nodes.Object_309.geometry} material={materials.shoo} />
          </group>
          <group name="Cube080_265" position={[-11.407, 55.777, 5.851]} scale={0}>
            <mesh name="Object_311" geometry={nodes.Object_311.geometry} material={materials.shoo} />
          </group>
          <group name="Cube081_266" position={[4.237, 55.777, 22.526]} scale={0}>
            <mesh name="Object_313" geometry={nodes.Object_313.geometry} material={materials.shoo} />
          </group>
          <group name="Cube082_267" position={[13.448, 55.777, -0.217]} scale={0}>
            <mesh name="Object_315" geometry={nodes.Object_315.geometry} material={materials.shoo} />
          </group>
          <group name="Cube083_268" position={[18.179, 55.777, 16.066]} scale={0}>
            <mesh name="Object_317" geometry={nodes.Object_317.geometry} material={materials.shoo} />
          </group>
          <group name="Cube084_269" position={[-8.94, 55.777, -14.034]} scale={0}>
            <mesh name="Object_319" geometry={nodes.Object_319.geometry} material={materials.shoo} />
          </group>
          <group name="Cube085_270" position={[-11.196, 55.777, 13.406]} scale={0}>
            <mesh name="Object_321" geometry={nodes.Object_321.geometry} material={materials.shoo} />
          </group>
          <group name="Cube086_271" position={[13.856, 55.777, -3.409]} scale={0}>
            <mesh name="Object_323" geometry={nodes.Object_323.geometry} material={materials.shoo} />
          </group>
          <group name="Cube087_272" position={[9.638, 55.777, 11.156]} scale={0}>
            <mesh name="Object_325" geometry={nodes.Object_325.geometry} material={materials.shoo} />
          </group>
          <group name="Cube088_273" position={[7.277, 55.777, 19.179]} scale={0}>
            <mesh name="Object_327" geometry={nodes.Object_327.geometry} material={materials.shoo} />
          </group>
          <group name="Cube089_274" position={[21.765, 55.777, 1.49]} scale={0}>
            <mesh name="Object_329" geometry={nodes.Object_329.geometry} material={materials.shoo} />
          </group>
          <group name="Cube090_275" position={[5.982, 55.777, -11.764]} scale={0}>
            <mesh name="Object_331" geometry={nodes.Object_331.geometry} material={materials.shoo} />
          </group>
          <group name="Cube091_276" position={[13.538, 55.777, -11.488]} scale={0}>
            <mesh name="Object_333" geometry={nodes.Object_333.geometry} material={materials.shoo} />
          </group>
          <group name="Cube092_277" position={[-0.15, 55.777, -13.149]} scale={0}>
            <mesh name="Object_335" geometry={nodes.Object_335.geometry} material={materials.shoo} />
          </group>
          <group name="Cube093_278" position={[-20.938, 55.777, -3.627]} scale={0}>
            <mesh name="Object_337" geometry={nodes.Object_337.geometry} material={materials.shoo} />
          </group>
          <group name="Cube094_279" position={[-2.31, 55.777, 12.345]} scale={0}>
            <mesh name="Object_339" geometry={nodes.Object_339.geometry} material={materials.shoo} />
          </group>
          <group name="Cube095_280" position={[-19.252, 55.777, 11.646]} scale={0}>
            <mesh name="Object_341" geometry={nodes.Object_341.geometry} material={materials.shoo} />
          </group>
          <group name="Cube096_281" position={[-9.448, 103.977, 14.465]} scale={[0.069, 12.406, 0.069]}>
            <mesh name="Object_343" geometry={nodes.Object_343.geometry} material={materials.shoo} />
          </group>
          <group name="Cube097_282" position={[17.283, 115.846, 7.868]} scale={[0.069, 15.12, 0.069]}>
            <mesh name="Object_345" geometry={nodes.Object_345.geometry} material={materials.shoo} />
          </group>
          <group name="Cube098_283" position={[-6.632, 120.721, -10.527]} scale={[0.069, 16.196, 0.069]}>
            <mesh name="Object_347" geometry={nodes.Object_347.geometry} material={materials.shoo} />
          </group>
          <group name="Cube099_284" position={[8.518, 126.66, -11.165]} scale={[0.069, 17.398, 0.069]}>
            <mesh name="Object_349" geometry={nodes.Object_349.geometry} material={materials.shoo} />
          </group>
          <group name="Cube100_285" position={[16.875, 124.945, -11.481]} scale={[0.069, 17.026, 0.069]}>
            <mesh name="Object_351" geometry={nodes.Object_351.geometry} material={materials.shoo} />
          </group>
          <group name="Cube101_286" position={[-4.505, 127.635, -19.584]} scale={[0.069, 17.618, 0.069]}>
            <mesh name="Object_353" geometry={nodes.Object_353.geometry} material={materials.shoo} />
          </group>
          <group name="Cube102_287" position={[-12.046, 128.541, -0.403]} scale={[0.069, 17.809, 0.069]}>
            <mesh name="Object_355" geometry={nodes.Object_355.geometry} material={materials.shoo} />
          </group>
          <group name="Cube103_288" position={[-14.19, 128.004, -7.654]} scale={0}>
            <mesh name="Object_357" geometry={nodes.Object_357.geometry} material={materials.shoo} />
          </group>
          <group name="Cube104_289" position={[-11.407, 56.844, 5.851]} scale={[0.069, 0.768, 0.069]}>
            <mesh name="Object_359" geometry={nodes.Object_359.geometry} material={materials.shoo} />
          </group>
          <group name="Cube105_290" position={[4.237, 73.888, 22.526]} scale={[0.069, 5.664, 0.069]}>
            <mesh name="Object_361" geometry={nodes.Object_361.geometry} material={materials.shoo} />
          </group>
          <group name="Cube106_291" position={[13.448, 86.032, -0.217]} scale={[0.069, 8.678, 0.069]}>
            <mesh name="Object_363" geometry={nodes.Object_363.geometry} material={materials.shoo} />
          </group>
          <group name="Cube107_292" position={[18.179, 77.125, 16.066]} scale={[0.069, 6.221, 0.069]}>
            <mesh name="Object_365" geometry={nodes.Object_365.geometry} material={materials.shoo} />
          </group>
          <group name="Cube108_293" position={[-8.94, 64.423, -14.034]} scale={[0.069, 3.043, 0.069]}>
            <mesh name="Object_367" geometry={nodes.Object_367.geometry} material={materials.shoo} />
          </group>
          <group name="Cube109_294" position={[-11.196, 85.013, 13.406]} scale={[0.069, 8.297, 0.069]}>
            <mesh name="Object_369" geometry={nodes.Object_369.geometry} material={materials.shoo} />
          </group>
          <group name="Cube110_295" position={[13.856, 96.214, -3.409]} scale={[0.069, 10.958, 0.069]}>
            <mesh name="Object_371" geometry={nodes.Object_371.geometry} material={materials.shoo} />
          </group>
          <group name="Cube111_296" position={[9.638, 92.389, 11.156]} scale={[0.069, 9.787, 0.069]}>
            <mesh name="Object_373" geometry={nodes.Object_373.geometry} material={materials.shoo} />
          </group>
          <group name="Cube112_297" position={[7.277, 88.473, 19.179]} scale={[0.069, 8.887, 0.069]}>
            <mesh name="Object_375" geometry={nodes.Object_375.geometry} material={materials.shoo} />
          </group>
          <group name="Cube113_298" position={[21.765, 105.484, 1.49]} scale={[0.069, 12.879, 0.069]}>
            <mesh name="Object_377" geometry={nodes.Object_377.geometry} material={materials.shoo} />
          </group>
          <group name="Cube114_299" position={[5.982, 112.97, -11.764]} scale={[0.069, 14.57, 0.069]}>
            <mesh name="Object_379" geometry={nodes.Object_379.geometry} material={materials.shoo} />
          </group>
          <group name="Cube115_300" position={[13.538, 117.56, -11.488]} scale={[0.069, 15.415, 0.069]}>
            <mesh name="Object_381" geometry={nodes.Object_381.geometry} material={materials.shoo} />
          </group>
          <group name="Cube116_301" position={[-0.15, 61.018, -13.149]} scale={0}>
            <mesh name="Object_383" geometry={nodes.Object_383.geometry} material={materials.shoo} />
          </group>
          <group name="Cube117_302" position={[-20.938, 55.935, -3.627]} scale={[0.069, 0.364, 0.069]}>
            <mesh name="Object_385" geometry={nodes.Object_385.geometry} material={materials.shoo} />
          </group>
          <group name="Cube118_303" position={[-2.31, 62.438, 12.345]} scale={[0.069, 2.825, 0.069]}>
            <mesh name="Object_387" geometry={nodes.Object_387.geometry} material={materials.shoo} />
          </group>
          <group name="Cube119_304" position={[-19.252, 55.849, 11.646]} scale={0}>
            <mesh name="Object_389" geometry={nodes.Object_389.geometry} material={materials.shoo} />
          </group>
          <group name="Cube120_305" position={[-9.448, 55.777, 14.465]} scale={0}>
            <mesh name="Object_391" geometry={nodes.Object_391.geometry} material={materials.shoo} />
          </group>
          <group name="Cube121_306" position={[17.283, 55.777, 7.868]} scale={0}>
            <mesh name="Object_393" geometry={nodes.Object_393.geometry} material={materials.shoo} />
          </group>
          <group name="Cube122_307" position={[-6.632, 55.777, -10.527]} scale={0}>
            <mesh name="Object_395" geometry={nodes.Object_395.geometry} material={materials.shoo} />
          </group>
          <group name="Cube123_308" position={[8.518, 55.777, -11.165]} scale={0}>
            <mesh name="Object_397" geometry={nodes.Object_397.geometry} material={materials.shoo} />
          </group>
          <group name="Cube124_309" position={[16.875, 55.777, -11.481]} scale={0}>
            <mesh name="Object_399" geometry={nodes.Object_399.geometry} material={materials.shoo} />
          </group>
          <group name="Cube125_310" position={[-4.505, 55.777, -19.584]} scale={0}>
            <mesh name="Object_401" geometry={nodes.Object_401.geometry} material={materials.shoo} />
          </group>
          <group name="Cube126_311" position={[-12.046, 55.777, -0.403]} scale={0}>
            <mesh name="Object_403" geometry={nodes.Object_403.geometry} material={materials.shoo} />
          </group>
          <group name="Cube127_312" position={[-14.19, 55.777, -7.654]} scale={0}>
            <mesh name="Object_405" geometry={nodes.Object_405.geometry} material={materials.shoo} />
          </group>
          <group name="Cube128_313" position={[-11.407, 55.777, 5.851]} scale={0}>
            <mesh name="Object_407" geometry={nodes.Object_407.geometry} material={materials.shoo} />
          </group>
          <group name="Cube129_314" position={[4.237, 55.777, 22.526]} scale={0}>
            <mesh name="Object_409" geometry={nodes.Object_409.geometry} material={materials.shoo} />
          </group>
          <group name="Cube130_315" position={[13.448, 55.777, -0.217]} scale={0}>
            <mesh name="Object_411" geometry={nodes.Object_411.geometry} material={materials.shoo} />
          </group>
          <group name="Cube131_316" position={[18.179, 55.777, 16.066]} scale={0}>
            <mesh name="Object_413" geometry={nodes.Object_413.geometry} material={materials.shoo} />
          </group>
          <group name="Cube132_317" position={[-8.94, 55.777, -14.034]} scale={0}>
            <mesh name="Object_415" geometry={nodes.Object_415.geometry} material={materials.shoo} />
          </group>
          <group name="Cube133_318" position={[-11.196, 55.777, 13.406]} scale={0}>
            <mesh name="Object_417" geometry={nodes.Object_417.geometry} material={materials.shoo} />
          </group>
          <group name="Cube134_319" position={[13.856, 55.777, -3.409]} scale={0}>
            <mesh name="Object_419" geometry={nodes.Object_419.geometry} material={materials.shoo} />
          </group>
          <group name="Cube135_320" position={[9.638, 55.777, 11.156]} scale={0}>
            <mesh name="Object_421" geometry={nodes.Object_421.geometry} material={materials.shoo} />
          </group>
          <group name="Cube136_321" position={[7.277, 55.777, 19.179]} scale={0}>
            <mesh name="Object_423" geometry={nodes.Object_423.geometry} material={materials.shoo} />
          </group>
          <group name="Cube137_322" position={[21.765, 55.777, 1.49]} scale={0}>
            <mesh name="Object_425" geometry={nodes.Object_425.geometry} material={materials.shoo} />
          </group>
          <group name="Cube138_323" position={[5.982, 55.777, -11.764]} scale={0}>
            <mesh name="Object_427" geometry={nodes.Object_427.geometry} material={materials.shoo} />
          </group>
          <group name="Cube139_324" position={[13.538, 55.777, -11.488]} scale={0}>
            <mesh name="Object_429" geometry={nodes.Object_429.geometry} material={materials.shoo} />
          </group>
          <group name="Cube140_325" position={[-0.15, 55.777, -13.149]} scale={0}>
            <mesh name="Object_431" geometry={nodes.Object_431.geometry} material={materials.shoo} />
          </group>
          <group name="Cube141_326" position={[-20.938, 55.777, -3.627]} scale={0}>
            <mesh name="Object_433" geometry={nodes.Object_433.geometry} material={materials.shoo} />
          </group>
          <group name="Cube142_327" position={[-2.31, 55.777, 12.345]} scale={0}>
            <mesh name="Object_435" geometry={nodes.Object_435.geometry} material={materials.shoo} />
          </group>
          <group name="Cube143_328" position={[-19.252, 55.777, 11.646]} scale={0}>
            <mesh name="Object_437" geometry={nodes.Object_437.geometry} material={materials.shoo} />
          </group>
          <group name="Cube144_429" position={[-2.06, 46.686, -17.154]} scale={0}>
            <mesh name="Object_439" geometry={nodes.Object_439.geometry} material={materials.shoo} />
          </group>
          <group name="Cube145_430" position={[-18.298, 46.686, 5.082]} scale={0}>
            <mesh name="Object_441" geometry={nodes.Object_441.geometry} material={materials.shoo} />
          </group>
          <group name="Cube146_431" position={[11.847, 46.686, 3.801]} scale={0}>
            <mesh name="Object_443" geometry={nodes.Object_443.geometry} material={materials.shoo} />
          </group>
          <group name="Cube147_432" position={[0.652, 46.686, 14.028]} scale={0}>
            <mesh name="Object_445" geometry={nodes.Object_445.geometry} material={materials.shoo} />
          </group>
          <group name="Cube148_433" position={[-5.547, 46.686, 19.642]} scale={0}>
            <mesh name="Object_447" geometry={nodes.Object_447.geometry} material={materials.shoo} />
          </group>
          <group name="Cube149_434" position={[16.04, 46.686, 12.106]} scale={0}>
            <mesh name="Object_449" geometry={nodes.Object_449.geometry} material={materials.shoo} />
          </group>
          <group name="Cube150_435" position={[9.487, 46.686, -7.435]} scale={0}>
            <mesh name="Object_451" geometry={nodes.Object_451.geometry} material={materials.shoo} />
          </group>
          <group name="Cube151_436" position={[15.79, 46.686, -3.257]} scale={0}>
            <mesh name="Object_453" geometry={nodes.Object_453.geometry} material={materials.shoo} />
          </group>
          <group name="Cube152_437" position={[4.977, 46.686, -11.814]} scale={0}>
            <mesh name="Object_455" geometry={nodes.Object_455.geometry} material={materials.shoo} />
          </group>
          <group name="Cube153_438" position={[-17.725, 46.686, -14.532]} scale={0}>
            <mesh name="Object_457" geometry={nodes.Object_457.geometry} material={materials.shoo} />
          </group>
          <group name="Cube154_439" position={[-10.162, 46.686, 8.811]} scale={0}>
            <mesh name="Object_459" geometry={nodes.Object_459.geometry} material={materials.shoo} />
          </group>
          <group name="Cube155_440" position={[-24.253, 46.686, -0.622]} scale={0}>
            <mesh name="Object_461" geometry={nodes.Object_461.geometry} material={materials.shoo} />
          </group>
          <group name="Cube156_441" position={[15.869, 46.686, 5.004]} scale={0}>
            <mesh name="Object_463" geometry={nodes.Object_463.geometry} material={materials.shoo} />
          </group>
          <group name="Cube157_442" position={[-0.041, 46.686, -17.466]} scale={0}>
            <mesh name="Object_465" geometry={nodes.Object_465.geometry} material={materials.shoo} />
          </group>
          <group name="Cube158_443" position={[-8.423, 46.686, 11.518]} scale={0}>
            <mesh name="Object_467" geometry={nodes.Object_467.geometry} material={materials.shoo} />
          </group>
          <group name="Cube159_444" position={[-14.554, 46.686, -2.351]} scale={0}>
            <mesh name="Object_469" geometry={nodes.Object_469.geometry} material={materials.shoo} />
          </group>
          <group name="Cube160_445" position={[-17.903, 46.686, -10.014]} scale={0}>
            <mesh name="Object_471" geometry={nodes.Object_471.geometry} material={materials.shoo} />
          </group>
          <group name="Cube161_446" position={[-17.631, 46.686, 12.848]} scale={0}>
            <mesh name="Object_473" geometry={nodes.Object_473.geometry} material={materials.shoo} />
          </group>
          <group name="Cube162_447" position={[2.98, 46.686, 12.857]} scale={0}>
            <mesh name="Object_475" geometry={nodes.Object_475.geometry} material={materials.shoo} />
          </group>
          <group name="Cube163_448" position={[-2.987, 46.686, 17.502]} scale={0}>
            <mesh name="Object_477" geometry={nodes.Object_477.geometry} material={materials.shoo} />
          </group>
          <group name="Cube164_449" position={[8.567, 46.686, 9.976]} scale={0}>
            <mesh name="Object_479" geometry={nodes.Object_479.geometry} material={materials.shoo} />
          </group>
          <group name="Cube165_450" position={[18.371, 46.686, -10.68]} scale={0}>
            <mesh name="Object_481" geometry={nodes.Object_481.geometry} material={materials.shoo} />
          </group>
          <group name="Cube166_451" position={[-6.166, 46.686, -10.941]} scale={0}>
            <mesh name="Object_483" geometry={nodes.Object_483.geometry} material={materials.shoo} />
          </group>
          <group name="Cube167_452" position={[7.262, 46.686, -21.296]} scale={0}>
            <mesh name="Object_485" geometry={nodes.Object_485.geometry} material={materials.shoo} />
          </group>
          <group name="Cube168_453" position={[-2.06, 109.755, -17.154]} scale={[0.069, 16.234, 0.069]}>
            <mesh name="Object_487" geometry={nodes.Object_487.geometry} material={materials.shoo} />
          </group>
          <group name="Cube169_454" position={[-18.298, 125.285, 5.082]} scale={[0.069, 19.784, 0.069]}>
            <mesh name="Object_489" geometry={nodes.Object_489.geometry} material={materials.shoo} />
          </group>
          <group name="Cube170_455" position={[11.847, 131.664, 3.801]} scale={[0.069, 21.193, 0.069]}>
            <mesh name="Object_491" geometry={nodes.Object_491.geometry} material={materials.shoo} />
          </group>
          <group name="Cube171_456" position={[0.652, 139.434, 14.028]} scale={[0.069, 22.765, 0.069]}>
            <mesh name="Object_493" geometry={nodes.Object_493.geometry} material={materials.shoo} />
          </group>
          <group name="Cube172_457" position={[-5.547, 137.191, 19.642]} scale={[0.069, 22.279, 0.069]}>
            <mesh name="Object_495" geometry={nodes.Object_495.geometry} material={materials.shoo} />
          </group>
          <group name="Cube173_458" position={[16.04, 140.711, 12.106]} scale={[0.069, 23.053, 0.069]}>
            <mesh name="Object_497" geometry={nodes.Object_497.geometry} material={materials.shoo} />
          </group>
          <group name="Cube174_459" position={[9.487, 141.896, -7.435]} scale={[0.069, 23.303, 0.069]}>
            <mesh name="Object_499" geometry={nodes.Object_499.geometry} material={materials.shoo} />
          </group>
          <group name="Cube175_460" position={[15.79, 141.194, -3.257]} scale={0}>
            <mesh name="Object_501" geometry={nodes.Object_501.geometry} material={materials.shoo} />
          </group>
          <group name="Cube176_461" position={[4.977, 48.082, -11.814]} scale={[0.069, 1.005, 0.069]}>
            <mesh name="Object_503" geometry={nodes.Object_503.geometry} material={materials.shoo} />
          </group>
          <group name="Cube177_462" position={[-17.725, 70.383, -14.532]} scale={[0.069, 7.411, 0.069]}>
            <mesh name="Object_505" geometry={nodes.Object_505.geometry} material={materials.shoo} />
          </group>
          <group name="Cube178_463" position={[-10.162, 86.274, 8.811]} scale={[0.069, 11.356, 0.069]}>
            <mesh name="Object_507" geometry={nodes.Object_507.geometry} material={materials.shoo} />
          </group>
          <group name="Cube179_464" position={[-24.253, 74.619, -0.622]} scale={[0.069, 8.14, 0.069]}>
            <mesh name="Object_509" geometry={nodes.Object_509.geometry} material={materials.shoo} />
          </group>
          <group name="Cube180_465" position={[15.869, 57.999, 5.004]} scale={[0.069, 3.982, 0.069]}>
            <mesh name="Object_511" geometry={nodes.Object_511.geometry} material={materials.shoo} />
          </group>
          <group name="Cube181_466" position={[-0.041, 84.94, -17.466]} scale={[0.069, 10.856, 0.069]}>
            <mesh name="Object_513" geometry={nodes.Object_513.geometry} material={materials.shoo} />
          </group>
          <group name="Cube182_467" position={[-8.423, 99.597, 11.518]} scale={[0.069, 14.338, 0.069]}>
            <mesh name="Object_515" geometry={nodes.Object_515.geometry} material={materials.shoo} />
          </group>
          <group name="Cube183_468" position={[-14.554, 94.592, -2.351]} scale={[0.069, 12.806, 0.069]}>
            <mesh name="Object_517" geometry={nodes.Object_517.geometry} material={materials.shoo} />
          </group>
          <group name="Cube184_469" position={[-17.903, 89.468, -10.014]} scale={[0.069, 11.628, 0.069]}>
            <mesh name="Object_519" geometry={nodes.Object_519.geometry} material={materials.shoo} />
          </group>
          <group name="Cube185_470" position={[-17.631, 111.727, 12.848]} scale={[0.069, 16.852, 0.069]}>
            <mesh name="Object_521" geometry={nodes.Object_521.geometry} material={materials.shoo} />
          </group>
          <group name="Cube186_471" position={[2.98, 121.522, 12.857]} scale={[0.069, 19.065, 0.069]}>
            <mesh name="Object_523" geometry={nodes.Object_523.geometry} material={materials.shoo} />
          </group>
          <group name="Cube187_472" position={[-2.987, 127.528, 17.502]} scale={[0.069, 20.17, 0.069]}>
            <mesh name="Object_525" geometry={nodes.Object_525.geometry} material={materials.shoo} />
          </group>
          <group name="Cube188_473" position={[8.567, 53.543, 9.976]} scale={0}>
            <mesh name="Object_527" geometry={nodes.Object_527.geometry} material={materials.shoo} />
          </group>
          <group name="Cube189_474" position={[18.371, 46.892, -10.68]} scale={[0.069, 0.477, 0.069]}>
            <mesh name="Object_529" geometry={nodes.Object_529.geometry} material={materials.shoo} />
          </group>
          <group name="Cube190_475" position={[-6.166, 55.401, -10.941]} scale={[0.069, 3.697, 0.069]}>
            <mesh name="Object_531" geometry={nodes.Object_531.geometry} material={materials.shoo} />
          </group>
          <group name="Cube191_476" position={[7.262, 46.779, -21.296]} scale={0}>
            <mesh name="Object_533" geometry={nodes.Object_533.geometry} material={materials.shoo} />
          </group>
          <group name="Cube192_477" position={[-2.06, 46.686, -17.154]} scale={0}>
            <mesh name="Object_535" geometry={nodes.Object_535.geometry} material={materials.shoo} />
          </group>
          <group name="Cube193_478" position={[-18.298, 46.686, 5.082]} scale={0}>
            <mesh name="Object_537" geometry={nodes.Object_537.geometry} material={materials.shoo} />
          </group>
          <group name="Cube194_479" position={[11.847, 46.686, 3.801]} scale={0}>
            <mesh name="Object_539" geometry={nodes.Object_539.geometry} material={materials.shoo} />
          </group>
          <group name="Cube195_480" position={[0.652, 46.686, 14.028]} scale={0}>
            <mesh name="Object_541" geometry={nodes.Object_541.geometry} material={materials.shoo} />
          </group>
          <group name="Cube196_481" position={[-5.547, 46.686, 19.642]} scale={0}>
            <mesh name="Object_543" geometry={nodes.Object_543.geometry} material={materials.shoo} />
          </group>
          <group name="Cube197_482" position={[16.04, 46.686, 12.106]} scale={0}>
            <mesh name="Object_545" geometry={nodes.Object_545.geometry} material={materials.shoo} />
          </group>
          <group name="Cube198_483" position={[9.487, 46.686, -7.435]} scale={0}>
            <mesh name="Object_547" geometry={nodes.Object_547.geometry} material={materials.shoo} />
          </group>
          <group name="Cube199_484" position={[15.79, 46.686, -3.257]} scale={0}>
            <mesh name="Object_549" geometry={nodes.Object_549.geometry} material={materials.shoo} />
          </group>
          <group name="Cube200_485" position={[4.977, 46.686, -11.814]} scale={0}>
            <mesh name="Object_551" geometry={nodes.Object_551.geometry} material={materials.shoo} />
          </group>
          <group name="Cube201_486" position={[-17.725, 46.686, -14.532]} scale={0}>
            <mesh name="Object_553" geometry={nodes.Object_553.geometry} material={materials.shoo} />
          </group>
          <group name="Cube202_487" position={[-10.162, 46.686, 8.811]} scale={0}>
            <mesh name="Object_555" geometry={nodes.Object_555.geometry} material={materials.shoo} />
          </group>
          <group name="Cube203_488" position={[-24.253, 46.686, -0.622]} scale={0}>
            <mesh name="Object_557" geometry={nodes.Object_557.geometry} material={materials.shoo} />
          </group>
          <group name="Cube204_489" position={[15.869, 46.686, 5.004]} scale={0}>
            <mesh name="Object_559" geometry={nodes.Object_559.geometry} material={materials.shoo} />
          </group>
          <group name="Cube205_490" position={[-0.041, 46.686, -17.466]} scale={0}>
            <mesh name="Object_561" geometry={nodes.Object_561.geometry} material={materials.shoo} />
          </group>
          <group name="Cube206_491" position={[-8.423, 46.686, 11.518]} scale={0}>
            <mesh name="Object_563" geometry={nodes.Object_563.geometry} material={materials.shoo} />
          </group>
          <group name="Cube207_492" position={[-14.554, 46.686, -2.351]} scale={0}>
            <mesh name="Object_565" geometry={nodes.Object_565.geometry} material={materials.shoo} />
          </group>
          <group name="Cube208_493" position={[-17.903, 46.686, -10.014]} scale={0}>
            <mesh name="Object_567" geometry={nodes.Object_567.geometry} material={materials.shoo} />
          </group>
          <group name="Cube209_494" position={[-17.631, 46.686, 12.848]} scale={0}>
            <mesh name="Object_569" geometry={nodes.Object_569.geometry} material={materials.shoo} />
          </group>
          <group name="Cube210_495" position={[2.98, 46.686, 12.857]} scale={0}>
            <mesh name="Object_571" geometry={nodes.Object_571.geometry} material={materials.shoo} />
          </group>
          <group name="Cube211_496" position={[-2.987, 46.686, 17.502]} scale={0}>
            <mesh name="Object_573" geometry={nodes.Object_573.geometry} material={materials.shoo} />
          </group>
          <group name="Cube212_497" position={[8.567, 46.686, 9.976]} scale={0}>
            <mesh name="Object_575" geometry={nodes.Object_575.geometry} material={materials.shoo} />
          </group>
          <group name="Cube213_498" position={[18.371, 46.686, -10.68]} scale={0}>
            <mesh name="Object_577" geometry={nodes.Object_577.geometry} material={materials.shoo} />
          </group>
          <group name="Cube214_499" position={[-6.166, 46.686, -10.941]} scale={0}>
            <mesh name="Object_579" geometry={nodes.Object_579.geometry} material={materials.shoo} />
          </group>
          <group name="Cube215_500" position={[7.262, 46.686, -21.296]} scale={0}>
            <mesh name="Object_581" geometry={nodes.Object_581.geometry} material={materials.shoo} />
          </group>
        </group>
        <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials['Material.001']} position={[0, -38.27, 0]} scale={1.764} />
      </group>
    </group>
  )
}

useGLTF.preload('../../public/img/website-transformed.glb')
